### PR TITLE
All services updated closes #4 #7 #6 #5 #3

### LINKED ISSUE #4: Create Service for Animals
Create basic service with Create, Edit and List forms.
Species and Breeds should link to their respective services.

### PR DESCRIPTION
**Pull request by smarbos**
Updated Services:
- Animals #4
- Contracts #5
- Humans #3

New Services:
- Breeds #7
- Species #6

### CODE REVIEW

**Comment by smarbos** [comment]
░░░░░░░░░░░░░░░░░░░░░░█████████
░░███████░░░░░░░░░░███▒▒▒▒▒▒▒▒███
░░█▒▒▒▒▒▒█░░░░░░░███▒▒▒▒▒▒▒▒▒▒▒▒▒███
░░░█▒▒▒▒▒▒█░░░░██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██
░░░░█▒▒▒▒▒█░░░██▒▒▒▒▒██▒▒▒▒▒▒██▒▒▒▒▒███
░░░░░█▒▒▒█░░░█▒▒▒▒▒▒████▒▒▒▒████▒▒▒▒▒▒██
░░░█████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██
░░░█▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒██
░██▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒██▒▒▒▒▒▒▒▒▒▒██▒▒▒▒██
██▒▒▒███████████▒▒▒▒▒██▒▒▒▒▒▒▒▒██▒▒▒▒▒██
█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒████████▒▒▒▒▒▒▒██
██▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██
░█▒▒▒███████████▒▒▒▒▒@anabellaspinelli ▒▒▒██
░██▒▒▒▒▒▒▒▒▒▒████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█
░░████████████░░░█████████████████

**Comment by anabellaspinelli** [comment]
Woo is thing working? I wanna try it out! 

Do I need to run the DB for it to work @smarbos ? Do we need docker lovin' for this?

**Comment by anabellaspinelli** [comment]
Also, watch out for these:

- `<ReferenceInput label="Team" source="_id" reference="teams" allowEmpty>` 👈 unedited copy-paste?
- `Species` is always written with an `s`, even if it's singular (like "caries" in spanish).

**Comment by smarbos** [comment]
Well.. This is working. What do you mean with "run the DB"? you need first to checkout to the "breeds-and-species" branch @ adopteitor-api.
make build
make run

and you are ready to go.

ABout the "teams" referenceInput, yes, its a copypaste, I'll clean this up. :+1:

**Pull request merged**
